= Vert.x高阶指南

Julien Viet <julien@julienviet.com>

本指南文档介绍了Vert.x的高级/底层内容

本文旨在解释和讨论以下内容


- Vert.x design
- Internal APIs
- Integration with Netty

You want to read this guide when you want to

- understand better Vert.x internals
- integrate Vert.x with thirdparty libraries
- perform networking with Netty and Vert.x

This is a live guide and you can contribute, just open a PR or an issue in the https://github.com/vert-x3/advanced-vertx-guide[repo].

WARNING: Some of the internal Vert.x APIs are exposed in this guide and you should keep in mind that these APIs are subject to
be changed when it is needed.



本指南文档介绍了Vert.x的高级/底层内容

本文旨在解释和讨论以下内容

- Vert.x的设计
- 内部API
- 与Netty集成

当你阅读本指南时你将：

- 更深入了解Vert.x
- 了解如何将Vert.x与其他第三方库集成
- 了解如何使用Netty和Vertx.x编写网络应用

这是一个实时指南，你可以做出贡献，只需在这个https://github.com/vert-x3/advanced-vertx-guide[仓库] 提交PR或者issue

WARNING: 谨记：本指南中介绍的一些Vert.x的内部API，这些API如必要会做相应变更。

include::Vertx_contexts.adoc[]

[[integrating-netty]]
include::Integrating_Netty.adoc[]

include::Using_Netty_codecs.adoc[]
